name: CI Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build clang:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:clang10

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run build
        run: Scripts/CIBuild.sh
      - name: Run pluginval
        run: Scripts/CIPluginval.sh

  Build gcc:
    runs-on: ubuntu-latest
    container: jackd13/audioplugins:gcc7

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Run build
        run: Scripts/CIBuild.sh
      - name: Run pluginval
        run: Scripts/CIPluginval.sh
